#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

using System.Runtime.Serialization;

	#region Dto Class
	
namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdUserRequestDto")]
	public partial class SdUserRequestDto
	{
		private int _serreqid;
		[DataMember(Name = "SerReqId", IsRequired = false)]
		public virtual int SerReqId 
		{ 
		    get
		    {
		        return this._serreqid;
		    }
		    set
		    {
		        this._serreqid = value;
		    }
		}
		
		private DateTime? _createdate;
		[DataMember(Name = "Createdate", IsRequired = false)]
		public virtual DateTime? Createdate 
		{ 
		    get
		    {
		        return this._createdate;
		    }
		    set
		    {
		        this._createdate = value;
		    }
		}
		
		private int? _currentstateid;
		[DataMember(Name = "Currentstateid", IsRequired = false)]
		public virtual int? Currentstateid 
		{ 
		    get
		    {
		        return this._currentstateid;
		    }
		    set
		    {
		        this._currentstateid = value;
		    }
		}
		
		private DateTime? _creditdate;
		[DataMember(Name = "Creditdate", IsRequired = false)]
		public virtual DateTime? Creditdate 
		{ 
		    get
		    {
		        return this._creditdate;
		    }
		    set
		    {
		        this._creditdate = value;
		    }
		}
		
		private int? _createuserid;
		[DataMember(Name = "Createuserid", IsRequired = false)]
		public virtual int? Createuserid 
		{ 
		    get
		    {
		        return this._createuserid;
		    }
		    set
		    {
		        this._createuserid = value;
		    }
		}
		
		private int? _owneruserid;
		[DataMember(Name = "Owneruserid", IsRequired = false)]
		public virtual int? Owneruserid 
		{ 
		    get
		    {
		        return this._owneruserid;
		    }
		    set
		    {
		        this._owneruserid = value;
		    }
		}
		
		private int? _servicecategoryjobid;
		[DataMember(Name = "Servicecategoryjobid", IsRequired = false)]
		public virtual int? Servicecategoryjobid 
		{ 
		    get
		    {
		        return this._servicecategoryjobid;
		    }
		    set
		    {
		        this._servicecategoryjobid = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private DateTime? _startdate;
		[DataMember(Name = "Startdate", IsRequired = false)]
		public virtual DateTime? Startdate 
		{ 
		    get
		    {
		        return this._startdate;
		    }
		    set
		    {
		        this._startdate = value;
		    }
		}
		
		private string _callnumber;
		[DataMember(Name = "Callnumber", IsRequired = false)]
		public virtual string Callnumber 
		{ 
		    get
		    {
		        return this._callnumber;
		    }
		    set
		    {
		        this._callnumber = value;
		    }
		}
		
		private int? _menuitemid;
		[DataMember(Name = "Menuitemid", IsRequired = false)]
		public virtual int? Menuitemid 
		{ 
		    get
		    {
		        return this._menuitemid;
		    }
		    set
		    {
		        this._menuitemid = value;
		    }
		}
		
		private DateTime? _enddate;
		[DataMember(Name = "Enddate", IsRequired = false)]
		public virtual DateTime? Enddate 
		{ 
		    get
		    {
		        return this._enddate;
		    }
		    set
		    {
		        this._enddate = value;
		    }
		}
		
		private int? _minestimatetime;
		[DataMember(Name = "Minestimatetime", IsRequired = false)]
		public virtual int? Minestimatetime 
		{ 
		    get
		    {
		        return this._minestimatetime;
		    }
		    set
		    {
		        this._minestimatetime = value;
		    }
		}
		
		private int? _maxestimatetime;
		[DataMember(Name = "Maxestimatetime", IsRequired = false)]
		public virtual int? Maxestimatetime 
		{ 
		    get
		    {
		        return this._maxestimatetime;
		    }
		    set
		    {
		        this._maxestimatetime = value;
		    }
		}
		
		private int? _transferid;
		[DataMember(Name = "Transferid", IsRequired = false)]
		public virtual int? Transferid 
		{ 
		    get
		    {
		        return this._transferid;
		    }
		    set
		    {
		        this._transferid = value;
		    }
		}
		
		private int? _groupingnumber;
		[DataMember(Name = "Groupingnumber", IsRequired = false)]
		public virtual int? Groupingnumber 
		{ 
		    get
		    {
		        return this._groupingnumber;
		    }
		    set
		    {
		        this._groupingnumber = value;
		    }
		}
		
		private int? _finalservicecategoryjobid;
		[DataMember(Name = "Finalservicecategoryjobid", IsRequired = false)]
		public virtual int? Finalservicecategoryjobid 
		{ 
		    get
		    {
		        return this._finalservicecategoryjobid;
		    }
		    set
		    {
		        this._finalservicecategoryjobid = value;
		    }
		}
		
		private string _finaldescription;
		[DataMember(Name = "Finaldescription", IsRequired = false)]
		public virtual string Finaldescription 
		{ 
		    get
		    {
		        return this._finaldescription;
		    }
		    set
		    {
		        this._finaldescription = value;
		    }
		}
		
		private int? _ownerchartid;
		[DataMember(Name = "OwnerChartId", IsRequired = false)]
		public virtual int? OwnerChartId 
		{ 
		    get
		    {
		        return this._ownerchartid;
		    }
		    set
		    {
		        this._ownerchartid = value;
		    }
		}
		
		private DateTime? _expiredate;
		[DataMember(Name = "ExpireDate", IsRequired = false)]
		public virtual DateTime? ExpireDate 
		{ 
		    get
		    {
		        return this._expiredate;
		    }
		    set
		    {
		        this._expiredate = value;
		    }
		}
		
		private short? _priority;
		[DataMember(Name = "Priority", IsRequired = false)]
		public virtual short? Priority 
		{ 
		    get
		    {
		        return this._priority;
		    }
		    set
		    {
		        this._priority = value;
		    }
		}
		
		private IList<SdRequestAttachmentDto> _sdrequestattachments = new List<SdRequestAttachmentDto>();
		[DataMember(Name = "SdRequestAttachments", IsRequired = false)]
		public virtual IList<SdRequestAttachmentDto> SdRequestAttachments 
		{ 
		    get
		    {
		        return this._sdrequestattachments;
		    }
		    set
		    {
		        this._sdrequestattachments = value;
		    }
		}
		
		private IList<SdRequestWorkDto> _sdrequestworks = new List<SdRequestWorkDto>();
		[DataMember(Name = "SdRequestWorks", IsRequired = false)]
		public virtual IList<SdRequestWorkDto> SdRequestWorks 
		{ 
		    get
		    {
		        return this._sdrequestworks;
		    }
		    set
		    {
		        this._sdrequestworks = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdServiceJobDto")]
	public partial class SdServiceJobDto
	{
		private int _servicejobid;
		[DataMember(Name = "ServiceJobId", IsRequired = false)]
		public virtual int ServiceJobId 
		{ 
		    get
		    {
		        return this._servicejobid;
		    }
		    set
		    {
		        this._servicejobid = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private IList<SdServiceCategoryJobDto> _sdservicecategoryjobs = new List<SdServiceCategoryJobDto>();
		[DataMember(Name = "SdServiceCategoryJobs", IsRequired = false)]
		public virtual IList<SdServiceCategoryJobDto> SdServiceCategoryJobs 
		{ 
		    get
		    {
		        return this._sdservicecategoryjobs;
		    }
		    set
		    {
		        this._sdservicecategoryjobs = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdServiceCategoryJobDto")]
	public partial class SdServiceCategoryJobDto
	{
		private int _servicecatjobid;
		[DataMember(Name = "ServiceCatJobId", IsRequired = false)]
		public virtual int ServiceCatJobId 
		{ 
		    get
		    {
		        return this._servicecatjobid;
		    }
		    set
		    {
		        this._servicecatjobid = value;
		    }
		}
		
		private int? _servicecategoryid;
		[DataMember(Name = "Servicecategoryid", IsRequired = false)]
		public virtual int? Servicecategoryid 
		{ 
		    get
		    {
		        return this._servicecategoryid;
		    }
		    set
		    {
		        this._servicecategoryid = value;
		    }
		}
		
		private int? _servicejobid;
		[DataMember(Name = "Servicejobid", IsRequired = false)]
		public virtual int? Servicejobid 
		{ 
		    get
		    {
		        return this._servicejobid;
		    }
		    set
		    {
		        this._servicejobid = value;
		    }
		}
		
		private int? _actionid;
		[DataMember(Name = "Actionid", IsRequired = false)]
		public virtual int? Actionid 
		{ 
		    get
		    {
		        return this._actionid;
		    }
		    set
		    {
		        this._actionid = value;
		    }
		}
		
		private short? _hasattachment;
		[DataMember(Name = "Hasattachment", IsRequired = false)]
		public virtual short? Hasattachment 
		{ 
		    get
		    {
		        return this._hasattachment;
		    }
		    set
		    {
		        this._hasattachment = value;
		    }
		}
		
		private short? _hasdescription;
		[DataMember(Name = "Hasdescription", IsRequired = false)]
		public virtual short? Hasdescription 
		{ 
		    get
		    {
		        return this._hasdescription;
		    }
		    set
		    {
		        this._hasdescription = value;
		    }
		}
		
		private int? _roleid;
		[DataMember(Name = "Roleid", IsRequired = false)]
		public virtual int? Roleid 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private short? _hascreditdate;
		[DataMember(Name = "Hascreditdate", IsRequired = false)]
		public virtual short? Hascreditdate 
		{ 
		    get
		    {
		        return this._hascreditdate;
		    }
		    set
		    {
		        this._hascreditdate = value;
		    }
		}
		
		private int? _estimatetimecost;
		[DataMember(Name = "Estimatetimecost", IsRequired = false)]
		public virtual int? Estimatetimecost 
		{ 
		    get
		    {
		        return this._estimatetimecost;
		    }
		    set
		    {
		        this._estimatetimecost = value;
		    }
		}
		
		private short? _isintree;
		[DataMember(Name = "Isintree", IsRequired = false)]
		public virtual short? Isintree 
		{ 
		    get
		    {
		        return this._isintree;
		    }
		    set
		    {
		        this._isintree = value;
		    }
		}
		
		private short? _precedence;
		[DataMember(Name = "Precedence", IsRequired = false)]
		public virtual short? Precedence 
		{ 
		    get
		    {
		        return this._precedence;
		    }
		    set
		    {
		        this._precedence = value;
		    }
		}
		
		private short? _multirequest;
		[DataMember(Name = "Multirequest", IsRequired = false)]
		public virtual short? Multirequest 
		{ 
		    get
		    {
		        return this._multirequest;
		    }
		    set
		    {
		        this._multirequest = value;
		    }
		}
		
		private short? _isinserter;
		[DataMember(Name = "IsInserter", IsRequired = false)]
		public virtual short? IsInserter 
		{ 
		    get
		    {
		        return this._isinserter;
		    }
		    set
		    {
		        this._isinserter = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdServiceCategoryDto")]
	public partial class SdServiceCategoryDto
	{
		private int _servicecatid;
		[DataMember(Name = "ServiceCatId", IsRequired = false)]
		public virtual int ServiceCatId 
		{ 
		    get
		    {
		        return this._servicecatid;
		    }
		    set
		    {
		        this._servicecatid = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private int? _parentid;
		[DataMember(Name = "Parentid", IsRequired = false)]
		public virtual int? Parentid 
		{ 
		    get
		    {
		        return this._parentid;
		    }
		    set
		    {
		        this._parentid = value;
		    }
		}
		
		private short? _hasjob;
		[DataMember(Name = "Hasjob", IsRequired = false)]
		public virtual short? Hasjob 
		{ 
		    get
		    {
		        return this._hasjob;
		    }
		    set
		    {
		        this._hasjob = value;
		    }
		}
		
		private short? _hasfilter;
		[DataMember(Name = "Hasfilter", IsRequired = false)]
		public virtual short? Hasfilter 
		{ 
		    get
		    {
		        return this._hasfilter;
		    }
		    set
		    {
		        this._hasfilter = value;
		    }
		}
		
		private short? _hasmenu;
		[DataMember(Name = "Hasmenu", IsRequired = false)]
		public virtual short? Hasmenu 
		{ 
		    get
		    {
		        return this._hasmenu;
		    }
		    set
		    {
		        this._hasmenu = value;
		    }
		}
		
		private short? _hasdevice;
		[DataMember(Name = "Hasdevice", IsRequired = false)]
		public virtual short? Hasdevice 
		{ 
		    get
		    {
		        return this._hasdevice;
		    }
		    set
		    {
		        this._hasdevice = value;
		    }
		}
		
		private IList<SdWorkDto> _sdworks = new List<SdWorkDto>();
		[DataMember(Name = "SdWorks", IsRequired = false)]
		public virtual IList<SdWorkDto> SdWorks 
		{ 
		    get
		    {
		        return this._sdworks;
		    }
		    set
		    {
		        this._sdworks = value;
		    }
		}
		
		private IList<SdServiceCategoryJobDto> _sdservicecategoryjobs = new List<SdServiceCategoryJobDto>();
		[DataMember(Name = "SdServiceCategoryJobs", IsRequired = false)]
		public virtual IList<SdServiceCategoryJobDto> SdServiceCategoryJobs 
		{ 
		    get
		    {
		        return this._sdservicecategoryjobs;
		    }
		    set
		    {
		        this._sdservicecategoryjobs = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdRequestStateDto")]
	public partial class SdRequestStateDto
	{
		private int _sdreqstateid;
		[DataMember(Name = "SdReqStateId", IsRequired = false)]
		public virtual int SdReqStateId 
		{ 
		    get
		    {
		        return this._sdreqstateid;
		    }
		    set
		    {
		        this._sdreqstateid = value;
		    }
		}
		
		private string _statetitle;
		[DataMember(Name = "StateTitle", IsRequired = false)]
		public virtual string StateTitle 
		{ 
		    get
		    {
		        return this._statetitle;
		    }
		    set
		    {
		        this._statetitle = value;
		    }
		}
		
		private IList<SdUserRequestDto> _sduserrequests = new List<SdUserRequestDto>();
		[DataMember(Name = "SdUserRequests", IsRequired = false)]
		public virtual IList<SdUserRequestDto> SdUserRequests 
		{ 
		    get
		    {
		        return this._sduserrequests;
		    }
		    set
		    {
		        this._sduserrequests = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdRequestProcessDto")]
	public partial class SdRequestProcessDto
	{
		private int _reqprocessid;
		[DataMember(Name = "ReqProcessId", IsRequired = false)]
		public virtual int ReqProcessId 
		{ 
		    get
		    {
		        return this._reqprocessid;
		    }
		    set
		    {
		        this._reqprocessid = value;
		    }
		}
		
		private int? _servicecategoryjobid;
		[DataMember(Name = "Servicecategoryjobid", IsRequired = false)]
		public virtual int? Servicecategoryjobid 
		{ 
		    get
		    {
		        return this._servicecategoryjobid;
		    }
		    set
		    {
		        this._servicecategoryjobid = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private DateTime? _processdate;
		[DataMember(Name = "Processdate", IsRequired = false)]
		public virtual DateTime? Processdate 
		{ 
		    get
		    {
		        return this._processdate;
		    }
		    set
		    {
		        this._processdate = value;
		    }
		}
		
		private int? _itexpertid;
		[DataMember(Name = "Itexpertid", IsRequired = false)]
		public virtual int? Itexpertid 
		{ 
		    get
		    {
		        return this._itexpertid;
		    }
		    set
		    {
		        this._itexpertid = value;
		    }
		}
		
		private long? _timecost;
		[DataMember(Name = "Timecost", IsRequired = false)]
		public virtual long? Timecost 
		{ 
		    get
		    {
		        return this._timecost;
		    }
		    set
		    {
		        this._timecost = value;
		    }
		}
		
		private int? _requestid;
		[DataMember(Name = "Requestid", IsRequired = false)]
		public virtual int? Requestid 
		{ 
		    get
		    {
		        return this._requestid;
		    }
		    set
		    {
		        this._requestid = value;
		    }
		}
		
		private int? _financialcost;
		[DataMember(Name = "Financialcost", IsRequired = false)]
		public virtual int? Financialcost 
		{ 
		    get
		    {
		        return this._financialcost;
		    }
		    set
		    {
		        this._financialcost = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdRequestAttachmentDto")]
	public partial class SdRequestAttachmentDto
	{
		private int _reuestattachid;
		[DataMember(Name = "ReuestAttachId", IsRequired = false)]
		public virtual int ReuestAttachId 
		{ 
		    get
		    {
		        return this._reuestattachid;
		    }
		    set
		    {
		        this._reuestattachid = value;
		    }
		}
		
		private int? _requestid;
		[DataMember(Name = "Requestid", IsRequired = false)]
		public virtual int? Requestid 
		{ 
		    get
		    {
		        return this._requestid;
		    }
		    set
		    {
		        this._requestid = value;
		    }
		}
		
		private string _filetype;
		[DataMember(Name = "Filetype", IsRequired = false)]
		public virtual string Filetype 
		{ 
		    get
		    {
		        return this._filetype;
		    }
		    set
		    {
		        this._filetype = value;
		    }
		}
		
		private string _filename;
		[DataMember(Name = "Filename", IsRequired = false)]
		public virtual string Filename 
		{ 
		    get
		    {
		        return this._filename;
		    }
		    set
		    {
		        this._filename = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private byte[] _content;
		[DataMember(Name = "Content", IsRequired = false)]
		public virtual byte[] Content 
		{ 
		    get
		    {
		        return this._content;
		    }
		    set
		    {
		        this._content = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdRequestAssignedExpertDto")]
	public partial class SdRequestAssignedExpertDto
	{
		private int _reqiestexpertid;
		[DataMember(Name = "ReqiestExpertId", IsRequired = false)]
		public virtual int ReqiestExpertId 
		{ 
		    get
		    {
		        return this._reqiestexpertid;
		    }
		    set
		    {
		        this._reqiestexpertid = value;
		    }
		}
		
		private int? _requestid;
		[DataMember(Name = "Requestid", IsRequired = false)]
		public virtual int? Requestid 
		{ 
		    get
		    {
		        return this._requestid;
		    }
		    set
		    {
		        this._requestid = value;
		    }
		}
		
		private DateTime? _assigndate;
		[DataMember(Name = "Assigndate", IsRequired = false)]
		public virtual DateTime? Assigndate 
		{ 
		    get
		    {
		        return this._assigndate;
		    }
		    set
		    {
		        this._assigndate = value;
		    }
		}
		
		private short? _assigntype;
		[DataMember(Name = "Assigntype", IsRequired = false)]
		public virtual short? Assigntype 
		{ 
		    get
		    {
		        return this._assigntype;
		    }
		    set
		    {
		        this._assigntype = value;
		    }
		}
		
		private short? _ishead;
		[DataMember(Name = "Ishead", IsRequired = false)]
		public virtual short? Ishead 
		{ 
		    get
		    {
		        return this._ishead;
		    }
		    set
		    {
		        this._ishead = value;
		    }
		}
		
		private int? _expertperid;
		[DataMember(Name = "ExpertPerId", IsRequired = false)]
		public virtual int? ExpertPerId 
		{ 
		    get
		    {
		        return this._expertperid;
		    }
		    set
		    {
		        this._expertperid = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdOfficeDto")]
	public partial class SdOfficeDto
	{
		private int _officeid;
		[DataMember(Name = "OfficeId", IsRequired = false)]
		public virtual int OfficeId 
		{ 
		    get
		    {
		        return this._officeid;
		    }
		    set
		    {
		        this._officeid = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private IList<SdItExpertDto> _sditexperts = new List<SdItExpertDto>();
		[DataMember(Name = "SdItExperts", IsRequired = false)]
		public virtual IList<SdItExpertDto> SdItExperts 
		{ 
		    get
		    {
		        return this._sditexperts;
		    }
		    set
		    {
		        this._sditexperts = value;
		    }
		}
		
		private IList<SdItRoleDto> _sditroles = new List<SdItRoleDto>();
		[DataMember(Name = "SdItRoles", IsRequired = false)]
		public virtual IList<SdItRoleDto> SdItRoles 
		{ 
		    get
		    {
		        return this._sditroles;
		    }
		    set
		    {
		        this._sditroles = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdItRoleExpertDto")]
	public partial class SdItRoleExpertDto
	{
		private int _roleexpertid;
		[DataMember(Name = "RoleExpertId", IsRequired = false)]
		public virtual int RoleExpertId 
		{ 
		    get
		    {
		        return this._roleexpertid;
		    }
		    set
		    {
		        this._roleexpertid = value;
		    }
		}
		
		private int? _expertid;
		[DataMember(Name = "Expertid", IsRequired = false)]
		public virtual int? Expertid 
		{ 
		    get
		    {
		        return this._expertid;
		    }
		    set
		    {
		        this._expertid = value;
		    }
		}
		
		private int? _itroleid;
		[DataMember(Name = "Itroleid", IsRequired = false)]
		public virtual int? Itroleid 
		{ 
		    get
		    {
		        return this._itroleid;
		    }
		    set
		    {
		        this._itroleid = value;
		    }
		}
		
		private short? _weight;
		[DataMember(Name = "Weight", IsRequired = false)]
		public virtual short? Weight 
		{ 
		    get
		    {
		        return this._weight;
		    }
		    set
		    {
		        this._weight = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdItRoleDto")]
	public partial class SdItRoleDto
	{
		private int _roleid;
		[DataMember(Name = "RoleId", IsRequired = false)]
		public virtual int RoleId 
		{ 
		    get
		    {
		        return this._roleid;
		    }
		    set
		    {
		        this._roleid = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private int? _officeid;
		[DataMember(Name = "Officeid", IsRequired = false)]
		public virtual int? Officeid 
		{ 
		    get
		    {
		        return this._officeid;
		    }
		    set
		    {
		        this._officeid = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private IList<SdItRoleExpertDto> _sditroleexperts = new List<SdItRoleExpertDto>();
		[DataMember(Name = "SdItRoleExperts", IsRequired = false)]
		public virtual IList<SdItRoleExpertDto> SdItRoleExperts 
		{ 
		    get
		    {
		        return this._sditroleexperts;
		    }
		    set
		    {
		        this._sditroleexperts = value;
		    }
		}
		
		private IList<SdServiceCategoryJobDto> _sdservicecategoryjobs = new List<SdServiceCategoryJobDto>();
		[DataMember(Name = "SdServiceCategoryJobs", IsRequired = false)]
		public virtual IList<SdServiceCategoryJobDto> SdServiceCategoryJobs 
		{ 
		    get
		    {
		        return this._sdservicecategoryjobs;
		    }
		    set
		    {
		        this._sdservicecategoryjobs = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdItExpertDto")]
	public partial class SdItExpertDto
	{
		private int _itexpertid;
		[DataMember(Name = "ItExpertId", IsRequired = false)]
		public virtual int ItExpertId 
		{ 
		    get
		    {
		        return this._itexpertid;
		    }
		    set
		    {
		        this._itexpertid = value;
		    }
		}
		
		private int? _userid;
		[DataMember(Name = "Userid", IsRequired = false)]
		public virtual int? Userid 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private int? _officeid;
		[DataMember(Name = "Officeid", IsRequired = false)]
		public virtual int? Officeid 
		{ 
		    get
		    {
		        return this._officeid;
		    }
		    set
		    {
		        this._officeid = value;
		    }
		}
		
		private short? _enabled;
		[DataMember(Name = "Enabled", IsRequired = false)]
		public virtual short? Enabled 
		{ 
		    get
		    {
		        return this._enabled;
		    }
		    set
		    {
		        this._enabled = value;
		    }
		}
		
		private IList<SdItRoleExpertDto> _sditroleexperts = new List<SdItRoleExpertDto>();
		[DataMember(Name = "SdItRoleExperts", IsRequired = false)]
		public virtual IList<SdItRoleExpertDto> SdItRoleExperts 
		{ 
		    get
		    {
		        return this._sditroleexperts;
		    }
		    set
		    {
		        this._sditroleexperts = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdFilterCategoryDto")]
	public partial class SdFilterCategoryDto
	{
		private int _filterid;
		[DataMember(Name = "FilterId", IsRequired = false)]
		public virtual int FilterId 
		{ 
		    get
		    {
		        return this._filterid;
		    }
		    set
		    {
		        this._filterid = value;
		    }
		}
		
		private int? _servicecaegoryid;
		[DataMember(Name = "Servicecaegoryid", IsRequired = false)]
		public virtual int? Servicecaegoryid 
		{ 
		    get
		    {
		        return this._servicecaegoryid;
		    }
		    set
		    {
		        this._servicecaegoryid = value;
		    }
		}
		
		private int? _menuparentid;
		[DataMember(Name = "Menuparentid", IsRequired = false)]
		public virtual int? Menuparentid 
		{ 
		    get
		    {
		        return this._menuparentid;
		    }
		    set
		    {
		        this._menuparentid = value;
		    }
		}
		
		private int? _objecttypeid;
		[DataMember(Name = "Objecttypeid", IsRequired = false)]
		public virtual int? Objecttypeid 
		{ 
		    get
		    {
		        return this._objecttypeid;
		    }
		    set
		    {
		        this._objecttypeid = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "VwPersonelDto")]
	public partial class VwPersonelDto
	{
		private int _positionid;
		[DataMember(Name = "PositionId", IsRequired = false)]
		public virtual int PositionId 
		{ 
		    get
		    {
		        return this._positionid;
		    }
		    set
		    {
		        this._positionid = value;
		    }
		}
		
		private string _positiondesc;
		[DataMember(Name = "PositionDesc", IsRequired = false)]
		public virtual string PositionDesc 
		{ 
		    get
		    {
		        return this._positiondesc;
		    }
		    set
		    {
		        this._positiondesc = value;
		    }
		}
		
		private short _pertype;
		[DataMember(Name = "PerType", IsRequired = false)]
		public virtual short PerType 
		{ 
		    get
		    {
		        return this._pertype;
		    }
		    set
		    {
		        this._pertype = value;
		    }
		}
		
		private int _perno;
		[DataMember(Name = "PerNo", IsRequired = false)]
		public virtual int PerNo 
		{ 
		    get
		    {
		        return this._perno;
		    }
		    set
		    {
		        this._perno = value;
		    }
		}
		
		private string _perlname;
		[DataMember(Name = "PerLname", IsRequired = false)]
		public virtual string PerLname 
		{ 
		    get
		    {
		        return this._perlname;
		    }
		    set
		    {
		        this._perlname = value;
		    }
		}
		
		private int _perid;
		[DataMember(Name = "PerId", IsRequired = false)]
		public virtual int PerId 
		{ 
		    get
		    {
		        return this._perid;
		    }
		    set
		    {
		        this._perid = value;
		    }
		}
		
		private string _perfname;
		[DataMember(Name = "PerFname", IsRequired = false)]
		public virtual string PerFname 
		{ 
		    get
		    {
		        return this._perfname;
		    }
		    set
		    {
		        this._perfname = value;
		    }
		}
		
		private string _nationalno;
		[DataMember(Name = "NationalNo", IsRequired = false)]
		public virtual string NationalNo 
		{ 
		    get
		    {
		        return this._nationalno;
		    }
		    set
		    {
		        this._nationalno = value;
		    }
		}
		
		private string _name;
		[DataMember(Name = "Name", IsRequired = false)]
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private short _isactivate;
		[DataMember(Name = "Isactivate", IsRequired = false)]
		public virtual short Isactivate 
		{ 
		    get
		    {
		        return this._isactivate;
		    }
		    set
		    {
		        this._isactivate = value;
		    }
		}
		
		private int? _independentid;
		[DataMember(Name = "IndependentId", IsRequired = false)]
		public virtual int? IndependentId 
		{ 
		    get
		    {
		        return this._independentid;
		    }
		    set
		    {
		        this._independentid = value;
		    }
		}
		
		private string _fullname;
		[DataMember(Name = "FullName", IsRequired = false)]
		public virtual string FullName 
		{ 
		    get
		    {
		        return this._fullname;
		    }
		    set
		    {
		        this._fullname = value;
		    }
		}
		
		private string _expiredate;
		[DataMember(Name = "ExpireDate", IsRequired = false)]
		public virtual string ExpireDate 
		{ 
		    get
		    {
		        return this._expiredate;
		    }
		    set
		    {
		        this._expiredate = value;
		    }
		}
		
		private string _enddate;
		[DataMember(Name = "EndDate", IsRequired = false)]
		public virtual string EndDate 
		{ 
		    get
		    {
		        return this._enddate;
		    }
		    set
		    {
		        this._enddate = value;
		    }
		}
		
		private int _chartid;
		[DataMember(Name = "ChartId", IsRequired = false)]
		public virtual int ChartId 
		{ 
		    get
		    {
		        return this._chartid;
		    }
		    set
		    {
		        this._chartid = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "ObjecttypeDto")]
	public partial class ObjecttypeDto
	{
		private int _objecttypeid;
		[DataMember(Name = "ObjecttypeId", IsRequired = false)]
		public virtual int ObjecttypeId 
		{ 
		    get
		    {
		        return this._objecttypeid;
		    }
		    set
		    {
		        this._objecttypeid = value;
		    }
		}
		
		private string _objecttypedesc;
		[DataMember(Name = "ObjecttypeDesc", IsRequired = false)]
		public virtual string ObjecttypeDesc 
		{ 
		    get
		    {
		        return this._objecttypedesc;
		    }
		    set
		    {
		        this._objecttypedesc = value;
		    }
		}
		
		private int _deliverable;
		[DataMember(Name = "Deliverable", IsRequired = false)]
		public virtual int Deliverable 
		{ 
		    get
		    {
		        return this._deliverable;
		    }
		    set
		    {
		        this._deliverable = value;
		    }
		}
		
		private short? _sizeable;
		[DataMember(Name = "Sizeable", IsRequired = false)]
		public virtual short? Sizeable 
		{ 
		    get
		    {
		        return this._sizeable;
		    }
		    set
		    {
		        this._sizeable = value;
		    }
		}
		
		private string _sizeabledesc;
		[DataMember(Name = "Sizeabledesc", IsRequired = false)]
		public virtual string Sizeabledesc 
		{ 
		    get
		    {
		        return this._sizeabledesc;
		    }
		    set
		    {
		        this._sizeabledesc = value;
		    }
		}
		
		private short? _denumerable;
		[DataMember(Name = "Denumerable", IsRequired = false)]
		public virtual short? Denumerable 
		{ 
		    get
		    {
		        return this._denumerable;
		    }
		    set
		    {
		        this._denumerable = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdRequestWorkDto")]
	public partial class SdRequestWorkDto
	{
		private int? _requestid;
		[DataMember(Name = "RequestId", IsRequired = false)]
		public virtual int? RequestId 
		{ 
		    get
		    {
		        return this._requestid;
		    }
		    set
		    {
		        this._requestid = value;
		    }
		}
		
		private string _description;
		[DataMember(Name = "Description", IsRequired = false)]
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private int? _userid;
		[DataMember(Name = "UserId", IsRequired = false)]
		public virtual int? UserId 
		{ 
		    get
		    {
		        return this._userid;
		    }
		    set
		    {
		        this._userid = value;
		    }
		}
		
		private DateTime? _createdate;
		[DataMember(Name = "CreateDate", IsRequired = false)]
		public virtual DateTime? CreateDate 
		{ 
		    get
		    {
		        return this._createdate;
		    }
		    set
		    {
		        this._createdate = value;
		    }
		}
		
		private int _requestworkid;
		[DataMember(Name = "RequestWorkId", IsRequired = false)]
		public virtual int RequestWorkId 
		{ 
		    get
		    {
		        return this._requestworkid;
		    }
		    set
		    {
		        this._requestworkid = value;
		    }
		}
		
		private int? _sdworkid;
		[DataMember(Name = "SdWorkId", IsRequired = false)]
		public virtual int? SdWorkId 
		{ 
		    get
		    {
		        return this._sdworkid;
		    }
		    set
		    {
		        this._sdworkid = value;
		    }
		}
		
		private int? _worktime;
		[DataMember(Name = "WorkTime", IsRequired = false)]
		public virtual int? WorkTime 
		{ 
		    get
		    {
		        return this._worktime;
		    }
		    set
		    {
		        this._worktime = value;
		    }
		}
		
		private int? _workcost;
		[DataMember(Name = "WorkCost", IsRequired = false)]
		public virtual int? WorkCost 
		{ 
		    get
		    {
		        return this._workcost;
		    }
		    set
		    {
		        this._workcost = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "SdWorkDto")]
	public partial class SdWorkDto
	{
		private int _workid;
		[DataMember(Name = "WorkId", IsRequired = false)]
		public virtual int WorkId 
		{ 
		    get
		    {
		        return this._workid;
		    }
		    set
		    {
		        this._workid = value;
		    }
		}
		
		private string _title;
		[DataMember(Name = "Title", IsRequired = false)]
		public virtual string Title 
		{ 
		    get
		    {
		        return this._title;
		    }
		    set
		    {
		        this._title = value;
		    }
		}
		
		private int? _estimatetime;
		[DataMember(Name = "EstimateTime", IsRequired = false)]
		public virtual int? EstimateTime 
		{ 
		    get
		    {
		        return this._estimatetime;
		    }
		    set
		    {
		        this._estimatetime = value;
		    }
		}
		
		private int? _estimatecost;
		[DataMember(Name = "EstimateCost", IsRequired = false)]
		public virtual int? EstimateCost 
		{ 
		    get
		    {
		        return this._estimatecost;
		    }
		    set
		    {
		        this._estimatecost = value;
		    }
		}
		
		private int? _sdservicecatid;
		[DataMember(Name = "SdServiceCatId", IsRequired = false)]
		public virtual int? SdServiceCatId 
		{ 
		    get
		    {
		        return this._sdservicecatid;
		    }
		    set
		    {
		        this._sdservicecatid = value;
		    }
		}
		
		private IList<SdRequestWorkDto> _sdrequestworks = new List<SdRequestWorkDto>();
		[DataMember(Name = "SdRequestWorks", IsRequired = false)]
		public virtual IList<SdRequestWorkDto> SdRequestWorks 
		{ 
		    get
		    {
		        return this._sdrequestworks;
		    }
		    set
		    {
		        this._sdrequestworks = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "RequestcartablecycleDto")]
	public partial class RequestcartablecycleDto
	{
		private string _servicejob;
		[DataMember(Name = "Servicejob", IsRequired = false)]
		public virtual string Servicejob 
		{ 
		    get
		    {
		        return this._servicejob;
		    }
		    set
		    {
		        this._servicejob = value;
		    }
		}
		
		private string _servicecategory;
		[DataMember(Name = "Servicecategory", IsRequired = false)]
		public virtual string Servicecategory 
		{ 
		    get
		    {
		        return this._servicecategory;
		    }
		    set
		    {
		        this._servicecategory = value;
		    }
		}
		
		private int? _serreqid;
		[DataMember(Name = "SerReqId", IsRequired = false)]
		public virtual int? SerReqId 
		{ 
		    get
		    {
		        return this._serreqid;
		    }
		    set
		    {
		        this._serreqid = value;
		    }
		}
		
		private string _sendtime;
		[DataMember(Name = "Sendtime", IsRequired = false)]
		public virtual string Sendtime 
		{ 
		    get
		    {
		        return this._sendtime;
		    }
		    set
		    {
		        this._sendtime = value;
		    }
		}
		
		private int _senderperid;
		[DataMember(Name = "SenderPerId", IsRequired = false)]
		public virtual int SenderPerId 
		{ 
		    get
		    {
		        return this._senderperid;
		    }
		    set
		    {
		        this._senderperid = value;
		    }
		}
		
		private string _sendernamefamily;
		[DataMember(Name = "SenderNameFamily", IsRequired = false)]
		public virtual string SenderNameFamily 
		{ 
		    get
		    {
		        return this._sendernamefamily;
		    }
		    set
		    {
		        this._sendernamefamily = value;
		    }
		}
		
		private DateTime? _senddate;
		[DataMember(Name = "SendDate", IsRequired = false)]
		public virtual DateTime? SendDate 
		{ 
		    get
		    {
		        return this._senddate;
		    }
		    set
		    {
		        this._senddate = value;
		    }
		}
		
		private int _receiverperid;
		[DataMember(Name = "ReceiverPerId", IsRequired = false)]
		public virtual int ReceiverPerId 
		{ 
		    get
		    {
		        return this._receiverperid;
		    }
		    set
		    {
		        this._receiverperid = value;
		    }
		}
		
		private string _receivernamefamily;
		[DataMember(Name = "ReceiverNameFamily", IsRequired = false)]
		public virtual string ReceiverNameFamily 
		{ 
		    get
		    {
		        return this._receivernamefamily;
		    }
		    set
		    {
		        this._receivernamefamily = value;
		    }
		}
		
		private short? _positiontypeid;
		[DataMember(Name = "PositionTypeId", IsRequired = false)]
		public virtual short? PositionTypeId 
		{ 
		    get
		    {
		        return this._positiontypeid;
		    }
		    set
		    {
		        this._positiontypeid = value;
		    }
		}
		
		private string _personelname;
		[DataMember(Name = "Personelname", IsRequired = false)]
		public virtual string Personelname 
		{ 
		    get
		    {
		        return this._personelname;
		    }
		    set
		    {
		        this._personelname = value;
		    }
		}
		
		private string _ownername;
		[DataMember(Name = "Ownername", IsRequired = false)]
		public virtual string Ownername 
		{ 
		    get
		    {
		        return this._ownername;
		    }
		    set
		    {
		        this._ownername = value;
		    }
		}
		
		private string _ownerchartname;
		[DataMember(Name = "OwnerChartName", IsRequired = false)]
		public virtual string OwnerChartName 
		{ 
		    get
		    {
		        return this._ownerchartname;
		    }
		    set
		    {
		        this._ownerchartname = value;
		    }
		}
		
		private string _noarchivedate;
		[DataMember(Name = "NoArchiveDate", IsRequired = false)]
		public virtual string NoArchiveDate 
		{ 
		    get
		    {
		        return this._noarchivedate;
		    }
		    set
		    {
		        this._noarchivedate = value;
		    }
		}
		
		private string _intialingcomment;
		[DataMember(Name = "IntialingComment", IsRequired = false)]
		public virtual string IntialingComment 
		{ 
		    get
		    {
		        return this._intialingcomment;
		    }
		    set
		    {
		        this._intialingcomment = value;
		    }
		}
		
		private DateTime? _cyclestatuschangedate;
		[DataMember(Name = "CyclestatusChangeDate", IsRequired = false)]
		public virtual DateTime? CyclestatusChangeDate 
		{ 
		    get
		    {
		        return this._cyclestatuschangedate;
		    }
		    set
		    {
		        this._cyclestatuschangedate = value;
		    }
		}
		
		private long? _cyclestatusid;
		[DataMember(Name = "CycleStatusId", IsRequired = false)]
		public virtual long? CycleStatusId 
		{ 
		    get
		    {
		        return this._cyclestatusid;
		    }
		    set
		    {
		        this._cyclestatusid = value;
		    }
		}
		
		private string _cyclestatusdesc;
		[DataMember(Name = "CycleStatusDesc", IsRequired = false)]
		public virtual string CycleStatusDesc 
		{ 
		    get
		    {
		        return this._cyclestatusdesc;
		    }
		    set
		    {
		        this._cyclestatusdesc = value;
		    }
		}
		
		private short _cyclerow;
		[DataMember(Name = "CycleRow", IsRequired = false)]
		public virtual short CycleRow 
		{ 
		    get
		    {
		        return this._cyclerow;
		    }
		    set
		    {
		        this._cyclerow = value;
		    }
		}
		
		private int _cycleid;
		[DataMember(Name = "CycleId", IsRequired = false)]
		public virtual int CycleId 
		{ 
		    get
		    {
		        return this._cycleid;
		    }
		    set
		    {
		        this._cycleid = value;
		    }
		}
		
		private DateTime? _createdate;
		[DataMember(Name = "Createdate", IsRequired = false)]
		public virtual DateTime? Createdate 
		{ 
		    get
		    {
		        return this._createdate;
		    }
		    set
		    {
		        this._createdate = value;
		    }
		}
		
		private short? _beterminated;
		[DataMember(Name = "BeTerminated", IsRequired = false)]
		public virtual short? BeTerminated 
		{ 
		    get
		    {
		        return this._beterminated;
		    }
		    set
		    {
		        this._beterminated = value;
		    }
		}
		
		private string _archivedate;
		[DataMember(Name = "ArchiveDate", IsRequired = false)]
		public virtual string ArchiveDate 
		{ 
		    get
		    {
		        return this._archivedate;
		    }
		    set
		    {
		        this._archivedate = value;
		    }
		}
		
		private int? _archivecode;
		[DataMember(Name = "ArchiveCode", IsRequired = false)]
		public virtual int? ArchiveCode 
		{ 
		    get
		    {
		        return this._archivecode;
		    }
		    set
		    {
		        this._archivecode = value;
		    }
		}
		
		private int? _actionparentid;
		[DataMember(Name = "ActionParentId", IsRequired = false)]
		public virtual int? ActionParentId 
		{ 
		    get
		    {
		        return this._actionparentid;
		    }
		    set
		    {
		        this._actionparentid = value;
		    }
		}
		
		private string _actionname;
		[DataMember(Name = "ActionName", IsRequired = false)]
		public virtual string ActionName 
		{ 
		    get
		    {
		        return this._actionname;
		    }
		    set
		    {
		        this._actionname = value;
		    }
		}
		
		private int _actionid;
		[DataMember(Name = "ActionId", IsRequired = false)]
		public virtual int ActionId 
		{ 
		    get
		    {
		        return this._actionid;
		    }
		    set
		    {
		        this._actionid = value;
		    }
		}
		
	}
}

namespace ISE.ServiceDesk.Common.DTO	
{
	[DataContract(Name = "VwHokmDto")]
	public partial class VwHokmDto
	{
		private string _telno;
		[DataMember(Name = "TelNo", IsRequired = false)]
		public virtual string TelNo 
		{ 
		    get
		    {
		        return this._telno;
		    }
		    set
		    {
		        this._telno = value;
		    }
		}
		
		private long? _statementno;
		[DataMember(Name = "StatementNo", IsRequired = false)]
		public virtual long? StatementNo 
		{ 
		    get
		    {
		        return this._statementno;
		    }
		    set
		    {
		        this._statementno = value;
		    }
		}
		
		private string _semattitle;
		[DataMember(Name = "SematTitle", IsRequired = false)]
		public virtual string SematTitle 
		{ 
		    get
		    {
		        return this._semattitle;
		    }
		    set
		    {
		        this._semattitle = value;
		    }
		}
		
		private int _prsno;
		[DataMember(Name = "PrsNo", IsRequired = false)]
		public virtual int PrsNo 
		{ 
		    get
		    {
		        return this._prsno;
		    }
		    set
		    {
		        this._prsno = value;
		    }
		}
		
		private string _postalcode;
		[DataMember(Name = "PostalCode", IsRequired = false)]
		public virtual string PostalCode 
		{ 
		    get
		    {
		        return this._postalcode;
		    }
		    set
		    {
		        this._postalcode = value;
		    }
		}
		
		private string _posttitle;
		[DataMember(Name = "PostTitle", IsRequired = false)]
		public virtual string PostTitle 
		{ 
		    get
		    {
		        return this._posttitle;
		    }
		    set
		    {
		        this._posttitle = value;
		    }
		}
		
		private int _postsrl;
		[DataMember(Name = "PostSrl", IsRequired = false)]
		public virtual int PostSrl 
		{ 
		    get
		    {
		        return this._postsrl;
		    }
		    set
		    {
		        this._postsrl = value;
		    }
		}
		
		private short? _positionlevel;
		[DataMember(Name = "Positionlevel", IsRequired = false)]
		public virtual short? Positionlevel 
		{ 
		    get
		    {
		        return this._positionlevel;
		    }
		    set
		    {
		        this._positionlevel = value;
		    }
		}
		
		private long? _perid;
		[DataMember(Name = "PerId", IsRequired = false)]
		public virtual long? PerId 
		{ 
		    get
		    {
		        return this._perid;
		    }
		    set
		    {
		        this._perid = value;
		    }
		}
		
		private string _namefamily;
		[DataMember(Name = "NameFamily", IsRequired = false)]
		public virtual string NameFamily 
		{ 
		    get
		    {
		        return this._namefamily;
		    }
		    set
		    {
		        this._namefamily = value;
		    }
		}
		
		private string _name;
		[DataMember(Name = "Name", IsRequired = false)]
		public virtual string Name 
		{ 
		    get
		    {
		        return this._name;
		    }
		    set
		    {
		        this._name = value;
		    }
		}
		
		private string _mobileno;
		[DataMember(Name = "MobileNo", IsRequired = false)]
		public virtual string MobileNo 
		{ 
		    get
		    {
		        return this._mobileno;
		    }
		    set
		    {
		        this._mobileno = value;
		    }
		}
		
		private string _melicode;
		[DataMember(Name = "MeliCode", IsRequired = false)]
		public virtual string MeliCode 
		{ 
		    get
		    {
		        return this._melicode;
		    }
		    set
		    {
		        this._melicode = value;
		    }
		}
		
		private string _jobtitle;
		[DataMember(Name = "JobTitle", IsRequired = false)]
		public virtual string JobTitle 
		{ 
		    get
		    {
		        return this._jobtitle;
		    }
		    set
		    {
		        this._jobtitle = value;
		    }
		}
		
		private int _jobsrl;
		[DataMember(Name = "JobSrl", IsRequired = false)]
		public virtual int JobSrl 
		{ 
		    get
		    {
		        return this._jobsrl;
		    }
		    set
		    {
		        this._jobsrl = value;
		    }
		}
		
		private string _jobcode;
		[DataMember(Name = "JobCode", IsRequired = false)]
		public virtual string JobCode 
		{ 
		    get
		    {
		        return this._jobcode;
		    }
		    set
		    {
		        this._jobcode = value;
		    }
		}
		
		private string _issudate;
		[DataMember(Name = "IssuDate", IsRequired = false)]
		public virtual string IssuDate 
		{ 
		    get
		    {
		        return this._issudate;
		    }
		    set
		    {
		        this._issudate = value;
		    }
		}
		
		private string _idno;
		[DataMember(Name = "IdNo", IsRequired = false)]
		public virtual string IdNo 
		{ 
		    get
		    {
		        return this._idno;
		    }
		    set
		    {
		        this._idno = value;
		    }
		}
		
		private short? _head;
		[DataMember(Name = "Head", IsRequired = false)]
		public virtual short? Head 
		{ 
		    get
		    {
		        return this._head;
		    }
		    set
		    {
		        this._head = value;
		    }
		}
		
		private string _fileno;
		[DataMember(Name = "FileNo", IsRequired = false)]
		public virtual string FileNo 
		{ 
		    get
		    {
		        return this._fileno;
		    }
		    set
		    {
		        this._fileno = value;
		    }
		}
		
		private string _family;
		[DataMember(Name = "Family", IsRequired = false)]
		public virtual string Family 
		{ 
		    get
		    {
		        return this._family;
		    }
		    set
		    {
		        this._family = value;
		    }
		}
		
		private long _emsalrpsrl;
		[DataMember(Name = "EmsalrpSrl", IsRequired = false)]
		public virtual long EmsalrpSrl 
		{ 
		    get
		    {
		        return this._emsalrpsrl;
		    }
		    set
		    {
		        this._emsalrpsrl = value;
		    }
		}
		
		private string _empldate;
		[DataMember(Name = "EmplDate", IsRequired = false)]
		public virtual string EmplDate 
		{ 
		    get
		    {
		        return this._empldate;
		    }
		    set
		    {
		        this._empldate = value;
		    }
		}
		
		private int _empblcpsrl;
		[DataMember(Name = "EmpblcpSrl", IsRequired = false)]
		public virtual int EmpblcpSrl 
		{ 
		    get
		    {
		        return this._empblcpsrl;
		    }
		    set
		    {
		        this._empblcpsrl = value;
		    }
		}
		
		private int? _ememptpsrl;
		[DataMember(Name = "EmemptpSrl", IsRequired = false)]
		public virtual int? EmemptpSrl 
		{ 
		    get
		    {
		        return this._ememptpsrl;
		    }
		    set
		    {
		        this._ememptpsrl = value;
		    }
		}
		
		private string _ememptpdes;
		[DataMember(Name = "EmemptpDes", IsRequired = false)]
		public virtual string EmemptpDes 
		{ 
		    get
		    {
		        return this._ememptpdes;
		    }
		    set
		    {
		        this._ememptpdes = value;
		    }
		}
		
		private string _emcostotitle;
		[DataMember(Name = "EmcostoTitle", IsRequired = false)]
		public virtual string EmcostoTitle 
		{ 
		    get
		    {
		        return this._emcostotitle;
		    }
		    set
		    {
		        this._emcostotitle = value;
		    }
		}
		
		private int _emcostosrlcostassign;
		[DataMember(Name = "EmcostoSrlCostAssign", IsRequired = false)]
		public virtual int EmcostoSrlCostAssign 
		{ 
		    get
		    {
		        return this._emcostosrlcostassign;
		    }
		    set
		    {
		        this._emcostosrlcostassign = value;
		    }
		}
		
		private int _emcostosrl;
		[DataMember(Name = "EmcostoSrl", IsRequired = false)]
		public virtual int EmcostoSrl 
		{ 
		    get
		    {
		        return this._emcostosrl;
		    }
		    set
		    {
		        this._emcostosrl = value;
		    }
		}
		
		private string _emcostoindependtitle;
		[DataMember(Name = "EmcostoIndependTitle", IsRequired = false)]
		public virtual string EmcostoIndependTitle 
		{ 
		    get
		    {
		        return this._emcostoindependtitle;
		    }
		    set
		    {
		        this._emcostoindependtitle = value;
		    }
		}
		
		private long _emcostoindependsrl;
		[DataMember(Name = "EmcostoIndependSrl", IsRequired = false)]
		public virtual long EmcostoIndependSrl 
		{ 
		    get
		    {
		        return this._emcostoindependsrl;
		    }
		    set
		    {
		        this._emcostoindependsrl = value;
		    }
		}
		
		private string _birthdate;
		[DataMember(Name = "BirthDate", IsRequired = false)]
		public virtual string BirthDate 
		{ 
		    get
		    {
		        return this._birthdate;
		    }
		    set
		    {
		        this._birthdate = value;
		    }
		}
		
		private string _address;
		[DataMember(Name = "Address", IsRequired = false)]
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
		        this._address = value;
		    }
		}
		
	}
}
	#endregion
	#pragma warning restore 1591
