#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ISE.ServiceDesk.Model;

namespace ISE.ServiceDesk.Model	
{
	public partial class EntitiesModel1 : OpenAccessContext, IEntitiesModel1UnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel1.rlinq");
		
		public EntitiesModel1()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EntitiesModel1(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel1(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EntitiesModel1(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EntitiesModel1(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<SdUserRequest> SdUserRequests 
		{
			get
			{
				return this.GetAll<SdUserRequest>();
			}
		}
		
		public IQueryable<SdServiceJob> SdServiceJobs 
		{
			get
			{
				return this.GetAll<SdServiceJob>();
			}
		}
		
		public IQueryable<SdServiceCategoryJob> SdServiceCategoryJobs 
		{
			get
			{
				return this.GetAll<SdServiceCategoryJob>();
			}
		}
		
		public IQueryable<SdServiceCategory> SdServiceCategories 
		{
			get
			{
				return this.GetAll<SdServiceCategory>();
			}
		}
		
		public IQueryable<SdRequestState> SdRequestStates 
		{
			get
			{
				return this.GetAll<SdRequestState>();
			}
		}
		
		public IQueryable<SdRequestProcess> SdRequestProcesses 
		{
			get
			{
				return this.GetAll<SdRequestProcess>();
			}
		}
		
		public IQueryable<SdRequestAttachment> SdRequestAttachments 
		{
			get
			{
				return this.GetAll<SdRequestAttachment>();
			}
		}
		
		public IQueryable<SdRequestAssignedExpert> SdRequestAssignedExperts 
		{
			get
			{
				return this.GetAll<SdRequestAssignedExpert>();
			}
		}
		
		public IQueryable<SdOffice> SdOffices 
		{
			get
			{
				return this.GetAll<SdOffice>();
			}
		}
		
		public IQueryable<SdItRoleExpert> SdItRoleExperts 
		{
			get
			{
				return this.GetAll<SdItRoleExpert>();
			}
		}
		
		public IQueryable<SdItRole> SdItRoles 
		{
			get
			{
				return this.GetAll<SdItRole>();
			}
		}
		
		public IQueryable<SdItExpert> SdItExperts 
		{
			get
			{
				return this.GetAll<SdItExpert>();
			}
		}
		
		public IQueryable<SdFilterCategory> SdFilterCategories 
		{
			get
			{
				return this.GetAll<SdFilterCategory>();
			}
		}
		
		public IQueryable<VwPersonel> VwPersonels 
		{
			get
			{
				return this.GetAll<VwPersonel>();
			}
		}
		
		public IQueryable<Objecttype> Objecttypes 
		{
			get
			{
				return this.GetAll<Objecttype>();
			}
		}
		
		public IQueryable<SdRequestWork> SdRequestWorks 
		{
			get
			{
				return this.GetAll<SdRequestWork>();
			}
		}
		
		public IQueryable<SdWork> SdWorks 
		{
			get
			{
				return this.GetAll<SdWork>();
			}
		}
		
		public IQueryable<Requestcartablecycle> Requestcartablecycles 
		{
			get
			{
				return this.GetAll<Requestcartablecycle>();
			}
		}
		
		public IQueryable<VwHokm> VwHokms 
		{
			get
			{
				return this.GetAll<VwHokm>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "Oracle";
			backend.ProviderName = "Oracle.DataAccess.Client";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EntitiesModel1.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EntitiesModel1.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEntitiesModel1UnitOfWork : IUnitOfWork
	{
		IQueryable<SdUserRequest> SdUserRequests
		{
			get;
		}
		IQueryable<SdServiceJob> SdServiceJobs
		{
			get;
		}
		IQueryable<SdServiceCategoryJob> SdServiceCategoryJobs
		{
			get;
		}
		IQueryable<SdServiceCategory> SdServiceCategories
		{
			get;
		}
		IQueryable<SdRequestState> SdRequestStates
		{
			get;
		}
		IQueryable<SdRequestProcess> SdRequestProcesses
		{
			get;
		}
		IQueryable<SdRequestAttachment> SdRequestAttachments
		{
			get;
		}
		IQueryable<SdRequestAssignedExpert> SdRequestAssignedExperts
		{
			get;
		}
		IQueryable<SdOffice> SdOffices
		{
			get;
		}
		IQueryable<SdItRoleExpert> SdItRoleExperts
		{
			get;
		}
		IQueryable<SdItRole> SdItRoles
		{
			get;
		}
		IQueryable<SdItExpert> SdItExperts
		{
			get;
		}
		IQueryable<SdFilterCategory> SdFilterCategories
		{
			get;
		}
		IQueryable<VwPersonel> VwPersonels
		{
			get;
		}
		IQueryable<Objecttype> Objecttypes
		{
			get;
		}
		IQueryable<SdRequestWork> SdRequestWorks
		{
			get;
		}
		IQueryable<SdWork> SdWorks
		{
			get;
		}
		IQueryable<Requestcartablecycle> Requestcartablecycles
		{
			get;
		}
		IQueryable<VwHokm> VwHokms
		{
			get;
		}
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdUserRequest
	{
		private int _serreqid;
		public virtual int SerReqId
		{
			get
			{
				return this._serreqid;
			}
			set
			{
				this._serreqid = value;
			}
		}
		
		private DateTime? _createdate;
		public virtual DateTime? Createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				this._createdate = value;
			}
		}
		
		private int? _currentstateid;
		public virtual int? Currentstateid
		{
			get
			{
				return this._currentstateid;
			}
			set
			{
				this._currentstateid = value;
			}
		}
		
		private DateTime? _creditdate;
		public virtual DateTime? Creditdate
		{
			get
			{
				return this._creditdate;
			}
			set
			{
				this._creditdate = value;
			}
		}
		
		private int? _createuserid;
		public virtual int? Createuserid
		{
			get
			{
				return this._createuserid;
			}
			set
			{
				this._createuserid = value;
			}
		}
		
		private int? _owneruserid;
		public virtual int? Owneruserid
		{
			get
			{
				return this._owneruserid;
			}
			set
			{
				this._owneruserid = value;
			}
		}
		
		private int? _servicecategoryjobid;
		public virtual int? Servicecategoryjobid
		{
			get
			{
				return this._servicecategoryjobid;
			}
			set
			{
				this._servicecategoryjobid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private DateTime? _startdate;
		public virtual DateTime? Startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				this._startdate = value;
			}
		}
		
		private string _callnumber;
		public virtual string Callnumber
		{
			get
			{
				return this._callnumber;
			}
			set
			{
				this._callnumber = value;
			}
		}
		
		private int? _menuitemid;
		public virtual int? Menuitemid
		{
			get
			{
				return this._menuitemid;
			}
			set
			{
				this._menuitemid = value;
			}
		}
		
		private DateTime? _enddate;
		public virtual DateTime? Enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				this._enddate = value;
			}
		}
		
		private int? _minestimatetime;
		public virtual int? Minestimatetime
		{
			get
			{
				return this._minestimatetime;
			}
			set
			{
				this._minestimatetime = value;
			}
		}
		
		private int? _maxestimatetime;
		public virtual int? Maxestimatetime
		{
			get
			{
				return this._maxestimatetime;
			}
			set
			{
				this._maxestimatetime = value;
			}
		}
		
		private int? _transferid;
		public virtual int? Transferid
		{
			get
			{
				return this._transferid;
			}
			set
			{
				this._transferid = value;
			}
		}
		
		private int? _groupingnumber;
		public virtual int? Groupingnumber
		{
			get
			{
				return this._groupingnumber;
			}
			set
			{
				this._groupingnumber = value;
			}
		}
		
		private int? _finalservicecategoryjobid;
		public virtual int? Finalservicecategoryjobid
		{
			get
			{
				return this._finalservicecategoryjobid;
			}
			set
			{
				this._finalservicecategoryjobid = value;
			}
		}
		
		private string _finaldescription;
		public virtual string Finaldescription
		{
			get
			{
				return this._finaldescription;
			}
			set
			{
				this._finaldescription = value;
			}
		}
		
		private int? _ownerchartid;
		public virtual int? OwnerChartId
		{
			get
			{
				return this._ownerchartid;
			}
			set
			{
				this._ownerchartid = value;
			}
		}
		
		private DateTime? _expiredate;
		public virtual DateTime? ExpireDate
		{
			get
			{
				return this._expiredate;
			}
			set
			{
				this._expiredate = value;
			}
		}
		
		private short? _priority;
		public virtual short? Priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		
		private SdRequestState _sdrequeststate;
		public virtual SdRequestState Sdrequeststate
		{
			get
			{
				return this._sdrequeststate;
			}
			set
			{
				this._sdrequeststate = value;
			}
		}
		
		private IList<SdRequestAttachment> _sdrequestattachments = new List<SdRequestAttachment>();
		public virtual IList<SdRequestAttachment> SdRequestAttachments
		{
			get
			{
				return this._sdrequestattachments;
			}
		}
		
		private IList<SdRequestWork> _sdrequestworks = new List<SdRequestWork>();
		public virtual IList<SdRequestWork> SdRequestWorks
		{
			get
			{
				return this._sdrequestworks;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdServiceJob
	{
		private int _servicejobid;
		public virtual int ServiceJobId
		{
			get
			{
				return this._servicejobid;
			}
			set
			{
				this._servicejobid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private IList<SdServiceCategoryJob> _sdservicecategoryjobs = new List<SdServiceCategoryJob>();
		public virtual IList<SdServiceCategoryJob> SdServiceCategoryJobs
		{
			get
			{
				return this._sdservicecategoryjobs;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdServiceCategoryJob
	{
		private int _servicecatjobid;
		public virtual int ServiceCatJobId
		{
			get
			{
				return this._servicecatjobid;
			}
			set
			{
				this._servicecatjobid = value;
			}
		}
		
		private int? _servicecategoryid;
		public virtual int? Servicecategoryid
		{
			get
			{
				return this._servicecategoryid;
			}
			set
			{
				this._servicecategoryid = value;
			}
		}
		
		private int? _servicejobid;
		public virtual int? Servicejobid
		{
			get
			{
				return this._servicejobid;
			}
			set
			{
				this._servicejobid = value;
			}
		}
		
		private int? _actionid;
		public virtual int? Actionid
		{
			get
			{
				return this._actionid;
			}
			set
			{
				this._actionid = value;
			}
		}
		
		private short? _hasattachment;
		public virtual short? Hasattachment
		{
			get
			{
				return this._hasattachment;
			}
			set
			{
				this._hasattachment = value;
			}
		}
		
		private short? _hasdescription;
		public virtual short? Hasdescription
		{
			get
			{
				return this._hasdescription;
			}
			set
			{
				this._hasdescription = value;
			}
		}
		
		private int? _roleid;
		public virtual int? Roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private short? _hascreditdate;
		public virtual short? Hascreditdate
		{
			get
			{
				return this._hascreditdate;
			}
			set
			{
				this._hascreditdate = value;
			}
		}
		
		private int? _estimatetimecost;
		public virtual int? Estimatetimecost
		{
			get
			{
				return this._estimatetimecost;
			}
			set
			{
				this._estimatetimecost = value;
			}
		}
		
		private short? _isintree;
		public virtual short? Isintree
		{
			get
			{
				return this._isintree;
			}
			set
			{
				this._isintree = value;
			}
		}
		
		private short? _precedence;
		public virtual short? Precedence
		{
			get
			{
				return this._precedence;
			}
			set
			{
				this._precedence = value;
			}
		}
		
		private short? _multirequest;
		public virtual short? Multirequest
		{
			get
			{
				return this._multirequest;
			}
			set
			{
				this._multirequest = value;
			}
		}
		
		private short? _isinserter;
		public virtual short? IsInserter
		{
			get
			{
				return this._isinserter;
			}
			set
			{
				this._isinserter = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private SdServiceJob _sdservicejob;
		public virtual SdServiceJob Sdservicejob
		{
			get
			{
				return this._sdservicejob;
			}
			set
			{
				this._sdservicejob = value;
			}
		}
		
		private SdItRole _sditrole;
		public virtual SdItRole Sditrole
		{
			get
			{
				return this._sditrole;
			}
			set
			{
				this._sditrole = value;
			}
		}
		
		private SdServiceCategory _sdservicecategory;
		public virtual SdServiceCategory Sdservicecategory
		{
			get
			{
				return this._sdservicecategory;
			}
			set
			{
				this._sdservicecategory = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdServiceCategory
	{
		private int _servicecatid;
		public virtual int ServiceCatId
		{
			get
			{
				return this._servicecatid;
			}
			set
			{
				this._servicecatid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private int? _parentid;
		public virtual int? Parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				this._parentid = value;
			}
		}
		
		private short? _hasjob;
		public virtual short? Hasjob
		{
			get
			{
				return this._hasjob;
			}
			set
			{
				this._hasjob = value;
			}
		}
		
		private short? _hasfilter;
		public virtual short? Hasfilter
		{
			get
			{
				return this._hasfilter;
			}
			set
			{
				this._hasfilter = value;
			}
		}
		
		private short? _hasmenu;
		public virtual short? Hasmenu
		{
			get
			{
				return this._hasmenu;
			}
			set
			{
				this._hasmenu = value;
			}
		}
		
		private short? _hasdevice;
		public virtual short? Hasdevice
		{
			get
			{
				return this._hasdevice;
			}
			set
			{
				this._hasdevice = value;
			}
		}
		
		private IList<SdWork> _sdworks = new List<SdWork>();
		public virtual IList<SdWork> SdWorks
		{
			get
			{
				return this._sdworks;
			}
		}
		
		private IList<SdServiceCategoryJob> _sdservicecategoryjobs = new List<SdServiceCategoryJob>();
		public virtual IList<SdServiceCategoryJob> SdServiceCategoryJobs
		{
			get
			{
				return this._sdservicecategoryjobs;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdRequestState
	{
		private int _sdreqstateid;
		public virtual int SdReqStateId
		{
			get
			{
				return this._sdreqstateid;
			}
			set
			{
				this._sdreqstateid = value;
			}
		}
		
		private string _statetitle;
		public virtual string StateTitle
		{
			get
			{
				return this._statetitle;
			}
			set
			{
				this._statetitle = value;
			}
		}
		
		private IList<SdUserRequest> _sduserrequests = new List<SdUserRequest>();
		public virtual IList<SdUserRequest> SdUserRequests
		{
			get
			{
				return this._sduserrequests;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdRequestProcess
	{
		private int _reqprocessid;
		public virtual int ReqProcessId
		{
			get
			{
				return this._reqprocessid;
			}
			set
			{
				this._reqprocessid = value;
			}
		}
		
		private int? _servicecategoryjobid;
		public virtual int? Servicecategoryjobid
		{
			get
			{
				return this._servicecategoryjobid;
			}
			set
			{
				this._servicecategoryjobid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private DateTime? _processdate;
		public virtual DateTime? Processdate
		{
			get
			{
				return this._processdate;
			}
			set
			{
				this._processdate = value;
			}
		}
		
		private int? _itexpertid;
		public virtual int? Itexpertid
		{
			get
			{
				return this._itexpertid;
			}
			set
			{
				this._itexpertid = value;
			}
		}
		
		private long? _timecost;
		public virtual long? Timecost
		{
			get
			{
				return this._timecost;
			}
			set
			{
				this._timecost = value;
			}
		}
		
		private int? _requestid;
		public virtual int? Requestid
		{
			get
			{
				return this._requestid;
			}
			set
			{
				this._requestid = value;
			}
		}
		
		private int? _financialcost;
		public virtual int? Financialcost
		{
			get
			{
				return this._financialcost;
			}
			set
			{
				this._financialcost = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdRequestAttachment
	{
		private int _reuestattachid;
		public virtual int ReuestAttachId
		{
			get
			{
				return this._reuestattachid;
			}
			set
			{
				this._reuestattachid = value;
			}
		}
		
		private int? _requestid;
		public virtual int? Requestid
		{
			get
			{
				return this._requestid;
			}
			set
			{
				this._requestid = value;
			}
		}
		
		private string _filetype;
		public virtual string Filetype
		{
			get
			{
				return this._filetype;
			}
			set
			{
				this._filetype = value;
			}
		}
		
		private string _filename;
		public virtual string Filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				this._filename = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private byte[] _content;
		public virtual byte[] Content
		{
			get
			{
				return this._content;
			}
			set
			{
				this._content = value;
			}
		}
		
		private SdUserRequest _sduserrequest;
		public virtual SdUserRequest Sduserrequest
		{
			get
			{
				return this._sduserrequest;
			}
			set
			{
				this._sduserrequest = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdRequestAssignedExpert
	{
		private int _reqiestexpertid;
		public virtual int ReqiestExpertId
		{
			get
			{
				return this._reqiestexpertid;
			}
			set
			{
				this._reqiestexpertid = value;
			}
		}
		
		private int? _requestid;
		public virtual int? Requestid
		{
			get
			{
				return this._requestid;
			}
			set
			{
				this._requestid = value;
			}
		}
		
		private DateTime? _assigndate;
		public virtual DateTime? Assigndate
		{
			get
			{
				return this._assigndate;
			}
			set
			{
				this._assigndate = value;
			}
		}
		
		private short? _assigntype;
		public virtual short? Assigntype
		{
			get
			{
				return this._assigntype;
			}
			set
			{
				this._assigntype = value;
			}
		}
		
		private short? _ishead;
		public virtual short? Ishead
		{
			get
			{
				return this._ishead;
			}
			set
			{
				this._ishead = value;
			}
		}
		
		private int? _expertperid;
		public virtual int? ExpertPerId
		{
			get
			{
				return this._expertperid;
			}
			set
			{
				this._expertperid = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdOffice
	{
		private int _officeid;
		public virtual int OfficeId
		{
			get
			{
				return this._officeid;
			}
			set
			{
				this._officeid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private IList<SdItExpert> _sditexperts = new List<SdItExpert>();
		public virtual IList<SdItExpert> SdItExperts
		{
			get
			{
				return this._sditexperts;
			}
		}
		
		private IList<SdItRole> _sditroles = new List<SdItRole>();
		public virtual IList<SdItRole> SdItRoles
		{
			get
			{
				return this._sditroles;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdItRoleExpert
	{
		private int _roleexpertid;
		public virtual int RoleExpertId
		{
			get
			{
				return this._roleexpertid;
			}
			set
			{
				this._roleexpertid = value;
			}
		}
		
		private int? _expertid;
		public virtual int? Expertid
		{
			get
			{
				return this._expertid;
			}
			set
			{
				this._expertid = value;
			}
		}
		
		private int? _itroleid;
		public virtual int? Itroleid
		{
			get
			{
				return this._itroleid;
			}
			set
			{
				this._itroleid = value;
			}
		}
		
		private short? _weight;
		public virtual short? Weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				this._weight = value;
			}
		}
		
		private SdItRole _sditrole;
		public virtual SdItRole Sditrole
		{
			get
			{
				return this._sditrole;
			}
			set
			{
				this._sditrole = value;
			}
		}
		
		private SdItExpert _sditexpert;
		public virtual SdItExpert Sditexpert
		{
			get
			{
				return this._sditexpert;
			}
			set
			{
				this._sditexpert = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdItRole
	{
		private int _roleid;
		public virtual int RoleId
		{
			get
			{
				return this._roleid;
			}
			set
			{
				this._roleid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int? _officeid;
		public virtual int? Officeid
		{
			get
			{
				return this._officeid;
			}
			set
			{
				this._officeid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private SdOffice _sdoffice;
		public virtual SdOffice Sdoffice
		{
			get
			{
				return this._sdoffice;
			}
			set
			{
				this._sdoffice = value;
			}
		}
		
		private IList<SdItRoleExpert> _sditroleexperts = new List<SdItRoleExpert>();
		public virtual IList<SdItRoleExpert> SdItRoleExperts
		{
			get
			{
				return this._sditroleexperts;
			}
		}
		
		private IList<SdServiceCategoryJob> _sdservicecategoryjobs = new List<SdServiceCategoryJob>();
		public virtual IList<SdServiceCategoryJob> SdServiceCategoryJobs
		{
			get
			{
				return this._sdservicecategoryjobs;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdItExpert
	{
		private int _itexpertid;
		public virtual int ItExpertId
		{
			get
			{
				return this._itexpertid;
			}
			set
			{
				this._itexpertid = value;
			}
		}
		
		private int? _userid;
		public virtual int? Userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private int? _officeid;
		public virtual int? Officeid
		{
			get
			{
				return this._officeid;
			}
			set
			{
				this._officeid = value;
			}
		}
		
		private short? _enabled;
		public virtual short? Enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				this._enabled = value;
			}
		}
		
		private SdOffice _sdoffice;
		public virtual SdOffice Sdoffice
		{
			get
			{
				return this._sdoffice;
			}
			set
			{
				this._sdoffice = value;
			}
		}
		
		private IList<SdItRoleExpert> _sditroleexperts = new List<SdItRoleExpert>();
		public virtual IList<SdItRoleExpert> SdItRoleExperts
		{
			get
			{
				return this._sditroleexperts;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdFilterCategory
	{
		private int _filterid;
		public virtual int FilterId
		{
			get
			{
				return this._filterid;
			}
			set
			{
				this._filterid = value;
			}
		}
		
		private int? _servicecaegoryid;
		public virtual int? Servicecaegoryid
		{
			get
			{
				return this._servicecaegoryid;
			}
			set
			{
				this._servicecaegoryid = value;
			}
		}
		
		private int? _menuparentid;
		public virtual int? Menuparentid
		{
			get
			{
				return this._menuparentid;
			}
			set
			{
				this._menuparentid = value;
			}
		}
		
		private int? _objecttypeid;
		public virtual int? Objecttypeid
		{
			get
			{
				return this._objecttypeid;
			}
			set
			{
				this._objecttypeid = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class VwPersonel
	{
		private int _positionid;
		public virtual int PositionId
		{
			get
			{
				return this._positionid;
			}
			set
			{
				this._positionid = value;
			}
		}
		
		private string _positiondesc;
		public virtual string PositionDesc
		{
			get
			{
				return this._positiondesc;
			}
			set
			{
				this._positiondesc = value;
			}
		}
		
		private short _pertype;
		public virtual short PerType
		{
			get
			{
				return this._pertype;
			}
			set
			{
				this._pertype = value;
			}
		}
		
		private int _perno;
		public virtual int PerNo
		{
			get
			{
				return this._perno;
			}
			set
			{
				this._perno = value;
			}
		}
		
		private string _perlname;
		public virtual string PerLname
		{
			get
			{
				return this._perlname;
			}
			set
			{
				this._perlname = value;
			}
		}
		
		private int _perid;
		public virtual int PerId
		{
			get
			{
				return this._perid;
			}
			set
			{
				this._perid = value;
			}
		}
		
		private string _perfname;
		public virtual string PerFname
		{
			get
			{
				return this._perfname;
			}
			set
			{
				this._perfname = value;
			}
		}
		
		private string _nationalno;
		public virtual string NationalNo
		{
			get
			{
				return this._nationalno;
			}
			set
			{
				this._nationalno = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private short _isactivate;
		public virtual short Isactivate
		{
			get
			{
				return this._isactivate;
			}
			set
			{
				this._isactivate = value;
			}
		}
		
		private int? _independentid;
		public virtual int? IndependentId
		{
			get
			{
				return this._independentid;
			}
			set
			{
				this._independentid = value;
			}
		}
		
		private string _fullname;
		public virtual string FullName
		{
			get
			{
				return this._fullname;
			}
			set
			{
				this._fullname = value;
			}
		}
		
		private string _expiredate;
		public virtual string ExpireDate
		{
			get
			{
				return this._expiredate;
			}
			set
			{
				this._expiredate = value;
			}
		}
		
		private string _enddate;
		public virtual string EndDate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				this._enddate = value;
			}
		}
		
		private int _chartid;
		public virtual int ChartId
		{
			get
			{
				return this._chartid;
			}
			set
			{
				this._chartid = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class Objecttype
	{
		private int _objecttypeid;
		public virtual int ObjecttypeId
		{
			get
			{
				return this._objecttypeid;
			}
			set
			{
				this._objecttypeid = value;
			}
		}
		
		private string _objecttypedesc;
		public virtual string ObjecttypeDesc
		{
			get
			{
				return this._objecttypedesc;
			}
			set
			{
				this._objecttypedesc = value;
			}
		}
		
		private int _deliverable;
		public virtual int Deliverable
		{
			get
			{
				return this._deliverable;
			}
			set
			{
				this._deliverable = value;
			}
		}
		
		private short? _sizeable;
		public virtual short? Sizeable
		{
			get
			{
				return this._sizeable;
			}
			set
			{
				this._sizeable = value;
			}
		}
		
		private string _sizeabledesc;
		public virtual string Sizeabledesc
		{
			get
			{
				return this._sizeabledesc;
			}
			set
			{
				this._sizeabledesc = value;
			}
		}
		
		private short? _denumerable;
		public virtual short? Denumerable
		{
			get
			{
				return this._denumerable;
			}
			set
			{
				this._denumerable = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdRequestWork
	{
		private int? _requestid;
		public virtual int? RequestId
		{
			get
			{
				return this._requestid;
			}
			set
			{
				this._requestid = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private int? _userid;
		public virtual int? UserId
		{
			get
			{
				return this._userid;
			}
			set
			{
				this._userid = value;
			}
		}
		
		private DateTime? _createdate;
		public virtual DateTime? CreateDate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				this._createdate = value;
			}
		}
		
		private int _requestworkid;
		public virtual int RequestWorkId
		{
			get
			{
				return this._requestworkid;
			}
			set
			{
				this._requestworkid = value;
			}
		}
		
		private int? _sdworkid;
		public virtual int? SdWorkId
		{
			get
			{
				return this._sdworkid;
			}
			set
			{
				this._sdworkid = value;
			}
		}
		
		private int? _worktime;
		public virtual int? WorkTime
		{
			get
			{
				return this._worktime;
			}
			set
			{
				this._worktime = value;
			}
		}
		
		private int? _workcost;
		public virtual int? WorkCost
		{
			get
			{
				return this._workcost;
			}
			set
			{
				this._workcost = value;
			}
		}
		
		private SdUserRequest _sduserrequest;
		public virtual SdUserRequest Sduserrequest
		{
			get
			{
				return this._sduserrequest;
			}
			set
			{
				this._sduserrequest = value;
			}
		}
		
		private SdWork _sdwork;
		public virtual SdWork Sdwork
		{
			get
			{
				return this._sdwork;
			}
			set
			{
				this._sdwork = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class SdWork
	{
		private int _workid;
		public virtual int WorkId
		{
			get
			{
				return this._workid;
			}
			set
			{
				this._workid = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int? _estimatetime;
		public virtual int? EstimateTime
		{
			get
			{
				return this._estimatetime;
			}
			set
			{
				this._estimatetime = value;
			}
		}
		
		private int? _estimatecost;
		public virtual int? EstimateCost
		{
			get
			{
				return this._estimatecost;
			}
			set
			{
				this._estimatecost = value;
			}
		}
		
		private int? _sdservicecatid;
		public virtual int? SdServiceCatId
		{
			get
			{
				return this._sdservicecatid;
			}
			set
			{
				this._sdservicecatid = value;
			}
		}
		
		private SdServiceCategory _sdservicecategory;
		public virtual SdServiceCategory Sdservicecategory
		{
			get
			{
				return this._sdservicecategory;
			}
			set
			{
				this._sdservicecategory = value;
			}
		}
		
		private IList<SdRequestWork> _sdrequestworks = new List<SdRequestWork>();
		public virtual IList<SdRequestWork> SdRequestWorks
		{
			get
			{
				return this._sdrequestworks;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class Requestcartablecycle
	{
		private string _servicejob;
		public virtual string Servicejob
		{
			get
			{
				return this._servicejob;
			}
			set
			{
				this._servicejob = value;
			}
		}
		
		private string _servicecategory;
		public virtual string Servicecategory
		{
			get
			{
				return this._servicecategory;
			}
			set
			{
				this._servicecategory = value;
			}
		}
		
		private int? _serreqid;
		public virtual int? SerReqId
		{
			get
			{
				return this._serreqid;
			}
			set
			{
				this._serreqid = value;
			}
		}
		
		private string _sendtime;
		public virtual string Sendtime
		{
			get
			{
				return this._sendtime;
			}
			set
			{
				this._sendtime = value;
			}
		}
		
		private int _senderperid;
		public virtual int SenderPerId
		{
			get
			{
				return this._senderperid;
			}
			set
			{
				this._senderperid = value;
			}
		}
		
		private string _sendernamefamily;
		public virtual string SenderNameFamily
		{
			get
			{
				return this._sendernamefamily;
			}
			set
			{
				this._sendernamefamily = value;
			}
		}
		
		private DateTime? _senddate;
		public virtual DateTime? SendDate
		{
			get
			{
				return this._senddate;
			}
			set
			{
				this._senddate = value;
			}
		}
		
		private int _receiverperid;
		public virtual int ReceiverPerId
		{
			get
			{
				return this._receiverperid;
			}
			set
			{
				this._receiverperid = value;
			}
		}
		
		private string _receivernamefamily;
		public virtual string ReceiverNameFamily
		{
			get
			{
				return this._receivernamefamily;
			}
			set
			{
				this._receivernamefamily = value;
			}
		}
		
		private short? _positiontypeid;
		public virtual short? PositionTypeId
		{
			get
			{
				return this._positiontypeid;
			}
			set
			{
				this._positiontypeid = value;
			}
		}
		
		private string _personelname;
		public virtual string Personelname
		{
			get
			{
				return this._personelname;
			}
			set
			{
				this._personelname = value;
			}
		}
		
		private string _ownername;
		public virtual string Ownername
		{
			get
			{
				return this._ownername;
			}
			set
			{
				this._ownername = value;
			}
		}
		
		private string _ownerchartname;
		public virtual string OwnerChartName
		{
			get
			{
				return this._ownerchartname;
			}
			set
			{
				this._ownerchartname = value;
			}
		}
		
		private string _noarchivedate;
		public virtual string NoArchiveDate
		{
			get
			{
				return this._noarchivedate;
			}
			set
			{
				this._noarchivedate = value;
			}
		}
		
		private string _intialingcomment;
		public virtual string IntialingComment
		{
			get
			{
				return this._intialingcomment;
			}
			set
			{
				this._intialingcomment = value;
			}
		}
		
		private DateTime? _cyclestatuschangedate;
		public virtual DateTime? CyclestatusChangeDate
		{
			get
			{
				return this._cyclestatuschangedate;
			}
			set
			{
				this._cyclestatuschangedate = value;
			}
		}
		
		private long? _cyclestatusid;
		public virtual long? CycleStatusId
		{
			get
			{
				return this._cyclestatusid;
			}
			set
			{
				this._cyclestatusid = value;
			}
		}
		
		private string _cyclestatusdesc;
		public virtual string CycleStatusDesc
		{
			get
			{
				return this._cyclestatusdesc;
			}
			set
			{
				this._cyclestatusdesc = value;
			}
		}
		
		private short _cyclerow;
		public virtual short CycleRow
		{
			get
			{
				return this._cyclerow;
			}
			set
			{
				this._cyclerow = value;
			}
		}
		
		private int _cycleid;
		public virtual int CycleId
		{
			get
			{
				return this._cycleid;
			}
			set
			{
				this._cycleid = value;
			}
		}
		
		private DateTime? _createdate;
		public virtual DateTime? Createdate
		{
			get
			{
				return this._createdate;
			}
			set
			{
				this._createdate = value;
			}
		}
		
		private short? _beterminated;
		public virtual short? BeTerminated
		{
			get
			{
				return this._beterminated;
			}
			set
			{
				this._beterminated = value;
			}
		}
		
		private string _archivedate;
		public virtual string ArchiveDate
		{
			get
			{
				return this._archivedate;
			}
			set
			{
				this._archivedate = value;
			}
		}
		
		private int? _archivecode;
		public virtual int? ArchiveCode
		{
			get
			{
				return this._archivecode;
			}
			set
			{
				this._archivecode = value;
			}
		}
		
		private int? _actionparentid;
		public virtual int? ActionParentId
		{
			get
			{
				return this._actionparentid;
			}
			set
			{
				this._actionparentid = value;
			}
		}
		
		private string _actionname;
		public virtual string ActionName
		{
			get
			{
				return this._actionname;
			}
			set
			{
				this._actionname = value;
			}
		}
		
		private int _actionid;
		public virtual int ActionId
		{
			get
			{
				return this._actionid;
			}
			set
			{
				this._actionid = value;
			}
		}
		
	}
}
namespace ISE.ServiceDesk.Model	
{
	public partial class VwHokm
	{
		private string _telno;
		public virtual string TelNo
		{
			get
			{
				return this._telno;
			}
			set
			{
				this._telno = value;
			}
		}
		
		private long? _statementno;
		public virtual long? StatementNo
		{
			get
			{
				return this._statementno;
			}
			set
			{
				this._statementno = value;
			}
		}
		
		private string _semattitle;
		public virtual string SematTitle
		{
			get
			{
				return this._semattitle;
			}
			set
			{
				this._semattitle = value;
			}
		}
		
		private int _prsno;
		public virtual int PrsNo
		{
			get
			{
				return this._prsno;
			}
			set
			{
				this._prsno = value;
			}
		}
		
		private string _postalcode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalcode;
			}
			set
			{
				this._postalcode = value;
			}
		}
		
		private string _posttitle;
		public virtual string PostTitle
		{
			get
			{
				return this._posttitle;
			}
			set
			{
				this._posttitle = value;
			}
		}
		
		private int _postsrl;
		public virtual int PostSrl
		{
			get
			{
				return this._postsrl;
			}
			set
			{
				this._postsrl = value;
			}
		}
		
		private short? _positionlevel;
		public virtual short? Positionlevel
		{
			get
			{
				return this._positionlevel;
			}
			set
			{
				this._positionlevel = value;
			}
		}
		
		private long? _perid;
		public virtual long? PerId
		{
			get
			{
				return this._perid;
			}
			set
			{
				this._perid = value;
			}
		}
		
		private string _namefamily;
		public virtual string NameFamily
		{
			get
			{
				return this._namefamily;
			}
			set
			{
				this._namefamily = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _mobileno;
		public virtual string MobileNo
		{
			get
			{
				return this._mobileno;
			}
			set
			{
				this._mobileno = value;
			}
		}
		
		private string _melicode;
		public virtual string MeliCode
		{
			get
			{
				return this._melicode;
			}
			set
			{
				this._melicode = value;
			}
		}
		
		private string _jobtitle;
		public virtual string JobTitle
		{
			get
			{
				return this._jobtitle;
			}
			set
			{
				this._jobtitle = value;
			}
		}
		
		private int _jobsrl;
		public virtual int JobSrl
		{
			get
			{
				return this._jobsrl;
			}
			set
			{
				this._jobsrl = value;
			}
		}
		
		private string _jobcode;
		public virtual string JobCode
		{
			get
			{
				return this._jobcode;
			}
			set
			{
				this._jobcode = value;
			}
		}
		
		private string _issudate;
		public virtual string IssuDate
		{
			get
			{
				return this._issudate;
			}
			set
			{
				this._issudate = value;
			}
		}
		
		private string _idno;
		public virtual string IdNo
		{
			get
			{
				return this._idno;
			}
			set
			{
				this._idno = value;
			}
		}
		
		private short? _head;
		public virtual short? Head
		{
			get
			{
				return this._head;
			}
			set
			{
				this._head = value;
			}
		}
		
		private string _fileno;
		public virtual string FileNo
		{
			get
			{
				return this._fileno;
			}
			set
			{
				this._fileno = value;
			}
		}
		
		private string _family;
		public virtual string Family
		{
			get
			{
				return this._family;
			}
			set
			{
				this._family = value;
			}
		}
		
		private long _emsalrpsrl;
		public virtual long EmsalrpSrl
		{
			get
			{
				return this._emsalrpsrl;
			}
			set
			{
				this._emsalrpsrl = value;
			}
		}
		
		private string _empldate;
		public virtual string EmplDate
		{
			get
			{
				return this._empldate;
			}
			set
			{
				this._empldate = value;
			}
		}
		
		private int _empblcpsrl;
		public virtual int EmpblcpSrl
		{
			get
			{
				return this._empblcpsrl;
			}
			set
			{
				this._empblcpsrl = value;
			}
		}
		
		private int? _ememptpsrl;
		public virtual int? EmemptpSrl
		{
			get
			{
				return this._ememptpsrl;
			}
			set
			{
				this._ememptpsrl = value;
			}
		}
		
		private string _ememptpdes;
		public virtual string EmemptpDes
		{
			get
			{
				return this._ememptpdes;
			}
			set
			{
				this._ememptpdes = value;
			}
		}
		
		private string _emcostotitle;
		public virtual string EmcostoTitle
		{
			get
			{
				return this._emcostotitle;
			}
			set
			{
				this._emcostotitle = value;
			}
		}
		
		private int _emcostosrlcostassign;
		public virtual int EmcostoSrlCostAssign
		{
			get
			{
				return this._emcostosrlcostassign;
			}
			set
			{
				this._emcostosrlcostassign = value;
			}
		}
		
		private int _emcostosrl;
		public virtual int EmcostoSrl
		{
			get
			{
				return this._emcostosrl;
			}
			set
			{
				this._emcostosrl = value;
			}
		}
		
		private string _emcostoindependtitle;
		public virtual string EmcostoIndependTitle
		{
			get
			{
				return this._emcostoindependtitle;
			}
			set
			{
				this._emcostoindependtitle = value;
			}
		}
		
		private long _emcostoindependsrl;
		public virtual long EmcostoIndependSrl
		{
			get
			{
				return this._emcostoindependsrl;
			}
			set
			{
				this._emcostoindependsrl = value;
			}
		}
		
		private string _birthdate;
		public virtual string BirthDate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				this._birthdate = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
	}
}
#pragma warning restore 1591
